CREATE DATABASE cursos
GO
USE cursos

CREATE TABLE curso
(CodCurso INT PRIMARY KEY,
 NomCurso VARCHAR(50) NOT NULL,
 Horas INT,
 Fecha DATE
 );
 
 CREATE TABLE trabajador
(CodTrab int PRIMARY KEY,
 NomTrab VARCHAR(50) NOT NULL,
 APeTrab VARCHAR(50) NOT NULL,
 FechNac DATE NOT NULL,
 Salario MONEY NOT NULL
 );
 	
CREATE TABLE cursado
(CodCursado INT PRIMARY KEY,
 CodCurso INT NOT NULL FOREIGN KEY REFERENCES curso(CodCurso) ON DELETE NO ACTION ON UPDATE CASCADE,
 CodTrab INT NOT NULL FOREIGN KEY REFERENCES trabajador(CodTrab) ON DELETE NO ACTION ON UPDATE CASCADE,
 Apto CHAR(1) NULL
 );
 
 